const frameData = {
  'frame-1': 'frames/frame-1.JPG',
  'frame-2': 'frames/frame-2.JPG',
  'frame-3': 'frames/frame-3.JPG',
  'frame-4': 'frames/frame-4.JPG',
  'frame-5': 'frames/frame-5.JPG',
  'frame-6': 'frames/frame-6.JPG',
  'frame-7': 'frames/frame-7.JPG',
  'frame-8': 'frames/frame-8.JPG',
  'frame-9': 'frames/frame-9.JPG',
  'frame-10': 'frames/frame-10.JPG',
  'frame-11': 'frames/frame-11.JPG',
  'frame-12': 'frames/frame-12.JPG',
  'frame-13': 'frames/frame-13.JPG',
  'frame-14': 'frames/frame-14.JPG',
  'frame-15': 'frames/frame-15.JPG',
  'frame-16': 'frames/frame-16.JPG',
  'frame-17': 'frames/frame-17.JPG',
  'frame-18': 'frames/frame-18.JPG',
}